Repository codeit-sprint-fullstack/1-Sprint-Mission-BE, pull requests merged in 2024-08, with the labels that each got.

#22 [이진우] sprint6
  .gitignore
  data/MongooseSchema.js
  data/mock.js
  data/postgreSQLSchema.js
  data/seed.js
  package-lock.json
  package.json
  requests.http
  src/config.js
  src/env.js
  src/main.mongoose.js
  src/main.postgreSQL.js
Labels: 최종제출

#36 [송영섭] mission6
  .gitignore
  express-mission/.env
  express-mission/app.js
  express-mission/data/mock.js
  express-mission/data/seed.js
  express-mission/models/Product.js
  express-mission/package-lock.json
  express-mission/package.json
  express-mission/request.http
Labels: 매운맛🔥, 최종제출

#38 [박성현] sprint6
  .gitIgnore
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 최종제출

#28 [임송이] sprint 6
  .gitignore
  README.md
  app.mjs
  controllers/productControllers.mjs
  data/mock.mjs
  data/seed.mjs
  db/conn.mjs
  loadEnvironment.mjs
  models/Product.mjs
  package-lock.json
  package.json
  routes/productRoutes.mjs
Labels: 매운맛🔥

#26 [박상훈] sprint6
  .gitignore
  README.md
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 매운맛🔥

#32 [김현우] sprint6
  .gitignore
  env.js
  main.js
  middlewares/asyncHandler.js
  middlewares/errorHandler.js
  model/product.js
  package-lock.json
  package.json
  routes/productRoutes.js
Labels: 매운맛🔥

#37 [고종민] sprint6
  .gitignore
  package-lock.json
  package.json
  screenshot/GET.JPG
  screenshot/PATCH.JPG
  screenshot/POST.JPG
  src/app.js
  src/asyncHandler.js
  src/data/mockData.js
  src/data/seed.js
  src/models/product.js
  src/route/products.js
Labels: 최종제출

#27 [김소희] sprint6
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  data/mock.js
  data/seed.js
  models/Product.js
  package.json
  server.js
Labels: 매운맛🔥, 최종제출

#31 [김민서] sprint6
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  mission6.js
  models/product.js
  package-lock.json
  package.json
  routes/productRoutes.js
  server.js
Labels: 매운맛🔥, 최종제출

#39 [정준호] sprint6
  .env
  .gitignore
  index.js
  models/Product.js
  package-lock.json
  package.json
  routes/products.js
  script/MockData
Labels: 순한맛🐑, 최종제출

#24 [주영은] sprint6
  .gitignore
  README.md
  index.js
  models/product.js
  package-lock.json
  package.json
  routes/asyncHandler.js
  routes/products.js
  service/productService.js
Labels: 매운맛🔥, 최종제출

#25 [김민수] sprint6
  .DS_Store
  .gitignore
  app.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 매운맛🔥, 최종제출

#35 [안재민] sprint6
  .gitignore
  package.json
  server/DataSchema.js
  server/express.js
  server/requests.http
Labels: 매운맛🔥, 최종제출

#54 [송영섭] mission 7
  .gitignore
  express-mission-prisma/.gitignore
  express-mission-prisma/app.js
  express-mission-prisma/http/freeCommend.http
  express-mission-prisma/http/noticeBoard.http
  express-mission-prisma/http/usedCommend.http
  express-mission-prisma/package-lock.json
  express-mission-prisma/package.json
  express-mission-prisma/prisma/migrations/migration_lock.toml
  express-mission-prisma/prisma/mock.js
  express-mission-prisma/prisma/schema.prisma
  express-mission-prisma/prisma/seed.js
  express-mission-prisma/struct.js
  express-mission/app.js
  express-mission/request.http
Labels: 매운맛🔥, 최종제출

#43 [이진우] sprint7
  .vscode/settings.json
  data/mockPostgreSQL.js
  data/postgreSQLSchema.js
  data/seedPostgreSQL.js
  http/mongoose/requests.http
  http/postgreSQL/article.http
  http/postgreSQL/articleComment.http
  http/postgreSQL/productComment.http
  package-lock.json
  package.json
  prisma/migrations/20240812044335_init/migration.sql
  prisma/migrations/20240812123956_/migration.sql
  prisma/migrations/20240815094230_add_new_comment_table/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/main.mongoose.js
  src/main.postgreSQL.js
  src/structs/article.js
  src/structs/comment.js
Labels: 최종제출

#51 [박성현] sprint7
  .gitignore
  app.js
  http/articles.http
  http/comments.http
  package-lock.json
  package.json
  prisma/migrations/20240817175810_add_article/migration.sql
  prisma/migrations/20240817182856_add_article_comment/migration.sql
  prisma/migrations/20240818030107_add/migration.sql
  prisma/migrations/20240818030257_modify/migration.sql
  prisma/migrations/20240818031245_modify/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seeding/mock.js
  prisma/seeding/seed.js
  structs.js
Labels: 최종제출

#49 [김민서] sprint7
  controllers/articleController.js
  controllers/commentController.js
  controllers/productController.js
  mission6.js
  package-lock.json
  package.json
  prisma/migrations/20240817165946_add_product/migration.sql
  prisma/migrations/20240817170752_add_article/migration.sql
  prisma/migrations/20240817171020_add_comment/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  routes/articleRoutes.js
  routes/commentRoutes.js
  routes/productRoutes.js
  server.js
Labels: 매운맛🔥, 최종제출

#45 [박상훈] sprint7
  .gitignore
  README.md
  app.js
  data/mock.js
  data/seed.js
  https/articles.http
  https/comments.http
  models/Product.js
  package-lock.json
  package.json
  prisma/migrations/20240815105949_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  requests.http
Labels: 매운맛🔥

#46 [탁우현] sprint7
  app.js
  env.js
  errorUtils.js
  package-lock.json
  package.json
  prisma/migrations/20240808054203_init/migration.sql
  prisma/migrations/20240808072608_name_rename/migration.sql
  prisma/migrations/20240808082710_comment_update/migration.sql
  prisma/migrations/20240812010509_create_product_model/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  routes/articles.js
  routes/comments.js
  routes/products.js
  routes/users.js
  structs/articleStruct.js
  structs/commentStruct.js
  structs/productStruct.js
Labels: 순한맛🐑

#47 [임송이] sprint 7
  .gitignore
  app.js
  app.mjs
  controllers/productControllers.mjs
  data/mock.mjs
  data/seed.mjs
  db/conn.mjs
  http/article.http
  http/comment.http
  http/products.http
  loadEnvironment.mjs
  models/Product.mjs
  package-lock.json
  package.json
  routes/productRoutes.mjs
  src/controllers/articleController.js
  src/controllers/commentController.js
  src/controllers/productController.js
  src/prisma/migrations/20240812061942_init/migration.sql
  src/prisma/migrations/20240812062921_add_tags_field_s_default_value/migration.sql
  src/prisma/migrations/20240812073702_alter_on_delete_on_comment_table/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/prisma/mock.js
  src/prisma/schema.prisma
  src/prisma/seed.js
  src/routes/articleRoutes.js
  src/routes/commentRoutes.js
  src/routes/productRoutes.js
  src/utils/asyncHandler.js
  src/validation/structs.js
Labels: 매운맛🔥

#41 [김소희] sprint7
  .gitignore
  README.md
  api/articles/articleRoutes.js
  api/comments/boardCommentRoutes.js
  api/comments/marketCommentRoutes.js
  api/products/productRoutes.js
  data/MarketProduct.js
  data/mock.js
  data/seed.js
  models/Product.js
  package.json
  prisma/migrations/20240810072402_init/migration.sql
  prisma/migrations/20240810090345_add_comment_model/migration.sql
  prisma/migrations/20240810165047_add_board_type_enum/migration.sql
  prisma/migrations/20240810173503_update_comment_model/migration.sql
  prisma/migrations/20240812044522_remove_unique_title/migration.sql
  prisma/migrations/20240812054032_add_article_comment_relationship/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seeds/Articles.js
  prisma/seeds/BoardComment.js
  prisma/seeds/MarketComment.js
  prisma/seeds/seedArticles.js
  prisma/seeds/seedBoardComment.js
  prisma/seeds/seedMarketComment.js
  server.js
Labels: 매운맛🔥, 최종제출

#40 [김현우] sprint 7
  controllers/articleController.js
  controllers/commentController.js
  controllers/marketItemController.js
  index.js
  main.js
  middlewares/asyncHandler.js
  middlewares/errorHandler.js
  model/product.js
  package-lock.json
  package.json
  prisma/migrations/20240814054208_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  prismaClient.js
  routes/articleCommentRoutes.js
  routes/articleRoutes.js
  routes/marketCommentRoutes.js
  routes/marketItemRoutes.js
  routes/productRoutes.js
  utils/customError.js
Labels: 매운맛🔥

#53 [강범준] sprint7
  .DS_Store
  .gitignore
  README.md
  http/articles.http
  http/comments.http
  prisma/api.js
  prisma/app.js
  prisma/migrations/20240818074338_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  seeding/mock.js
  seeding/seed.js
Labels: 미완성🫠, 순한맛🐑

#50 [김효인] sprint7
  .github/pull-request-template.md
  .github/workflows/pull-request-template.md
  .gitignore
  app.js
  package-lock.json
  package.json
  prisma/data/mock.js
  prisma/data/seed.js
  prisma/migrations/20240815061317_imit/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  products_data/mock.js
  products_data/seed.js
  requests.http
  route/articles.js
  route/asyncHandler.js
  route/comments.js
  route/products.js
  route/struct.js
  route/users.js
Labels: 최종제출

#48 [주영은] sprint7
  Common/asyncHandler.js
  README.md
  index.js
  models/product.js
  package-lock.json
  package.json
  prisma/migrations/20240808052735_init/migration.sql
  prisma/migrations/20240809012444_ondelete/migration.sql
  prisma/migrations/20240809041233_update_articlecomment/migration.sql
  prisma/migrations/20240809043205_create_productcomments/migration.sql
  prisma/migrations/20240812044953_create_product/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.js
  routes/articleComments.js
  routes/articles.js
  routes/productComments.js
  routes/products.js
  service/articleCommentService.js
  service/articleService.js
  service/productCommentService.js
  service/productService.js
Labels: 매운맛🔥, 최종제출

#42 [안재민] Sprint7
  .gitignore
  app.js
  http/article.http
  package-lock.json
  package.json
  prisma/migrations/20240814042448_init/migration.sql
  prisma/migrations/20240814091254_add_model_comment/migration.sql
  prisma/migrations/20240815062032_add_comment_product/migration.sql
  prisma/migrations/20240815063107_add_comment_product_and_article_optional/migration.sql
  prisma/migrations/20240815070118_add_comment_on_delete/migration.sql
  prisma/migrations/20240815072427_temporary_comment_product/migration.sql
  prisma/migrations/20240815072508_temporary_comment_product/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  routes/articleComments.js
  routes/articles.js
  routes/productComments.js
  routes/products.js
  structs.js
  utils/asyncHandler.js
Labels: 매운맛🔥, 최종제출
