Repository codeit-sprint-fullstack/1-Sprint-Mission-BE, pull requests merged in 2024-10, with the labels that each got.

#66 [주영은] sprint10
  .gitignore
  Common/asyncHandler.js
  controllers/articleController.js
  controllers/authController.js
  controllers/commentController.js
  controllers/productController.js
  controllers/userController.js
  index.js
  middlewares/errorHandler.js
  middlewares/imageUpload.js
  middlewares/validateArticle.js
  middlewares/validateProductFields.js
  middlewares/verifyToken.js
  models/index.js
  package-lock.json
  package.json
  prisma/migrations/20240808052735_init/migration.sql
  prisma/migrations/20240809012444_ondelete/migration.sql
  prisma/migrations/20240809041233_update_articlecomment/migration.sql
  prisma/migrations/20240809043205_create_productcomments/migration.sql
  prisma/migrations/20240812044953_create_product/migration.sql
  prisma/migrations/20241005073631_plz/migration.sql
  prisma/migrations/20241005074221_is_favorite/migration.sql
  prisma/migrations/20241005150322_image_edit/migration.sql
  prisma/migrations/20241009054211_article_images/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  routes/articleComments.js
  routes/articleRoutes.js
  routes/articles.js
  routes/asyncHandler.js
  routes/authRoutes.js
  routes/commentRoutes.js
  routes/productComments.js
  routes/productRoutes.js
  routes/products.js
  routes/userRoutes.js
  service/articleCommentService.js
  service/articleService.js
  service/productCommentService.js
  service/productService.js
  services/articleService.js
  services/authService.js
  services/commentService.js
  services/productService.js
  services/userService.js
  swagger.js
  swagger_output.json
Labels: 매운맛🔥, 최종제출

#63 [탁우현] sprint10
  .gitignore
  app.js
  config/cookiesConfig.js
  config/passportConfig.js
  env.js
  middlewares/authUser.js
  middlewares/errorHandler.js
  middlewares/passport/jwtToken.js
  model/articleModel.js
  model/commentModel.js
  model/productModel.js
  model/userModel.js
  models/product.js
  package-lock.json
  package.json
  prisma/migrations/20240906052222_8_seed/migration.sql
  prisma/mock_2.js
  prisma/schema.prisma
  prisma/seed.js
  routes/articles.js
  routes/comments.js
  routes/products.js
  routes/users.js
  service/articleService.js
  service/commentService.js
  service/productService.js
  service/userService.js
  structs/articleStruct.js
  structs/commentStruct.js
  structs/productStruct.js
  swagger_output.json
  utils/errorUtils.js
  utils/orderByQuery.js
  utils/prismaClient.js
Labels: 최종제출

#64 [강범준] sprint10
  .DS_Store
  .gitignore
  README.md
  http/articles.http
  http/auth.http
  http/comments.http
  nodemon.json
  package-lock.json
  package.json
  prisma/migrations/20241004054952_init/migration.sql
  prisma/migrations/20241007130911_20231007_add_entire_data_models/migration.sql
  prisma/schema.prisma
  src/app.js
  src/controllers/articleController.js
  src/controllers/authController.js
  src/controllers/commentController.js
  src/controllers/imageController.js
  src/controllers/likeController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/authMiddleware.js
  src/middlewares/errorMiddleware.js
  src/middlewares/validate.js
  src/models/articleModel.js
  src/models/commentModel.js
  src/models/productModel.js
  src/models/userModel.js
  src/routes/articleRoutes.js
  src/routes/authRoutes.js
  src/routes/commentRoutes.js
  src/routes/imageRoutes.js
  src/routes/index.js
  src/routes/likeRoutes.js
  src/routes/productRoutes.js
  src/routes/userRoutes.js
  src/services/articleService.js
  src/services/authService.js
  src/services/commentService.js
  src/services/imageService.js
  src/services/likeService.js
  src/services/productService.js
  src/services/userService.js
  src/utils/asyncHandler.js
  src/utils/prisma.js
Labels: 진행중

#61 [김민수] sprint 10
  .DS_Store
  app.js
  index.js
  main.js
  models/Product.js
  package-lock.json
  package.json
  prisma/migrations/20240809081833_/migration.sql
  prisma/migrations/20240810065151_add_article_comments/migration.sql
  prisma/migrations/20240812062302_add_product/migration.sql
  prisma/migrations/20240812063949_testproduct/migration.sql
  prisma/migrations/20240812070206_test/migration.sql
  prisma/migrations/20241007044621_created_at/migration.sql
  prisma/migrations/20241007053851_testests/migration.sql
  prisma/migrations/20241007062203_dsfghjhjg/migration.sql
  prisma/migrations/20241008003818_fdgsdhfjds/migration.sql
  prisma/migrations/20241008004259_fdasghmd/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  requests.http
  src/controllers/articleController.js
  src/controllers/authController.js
  src/controllers/commentController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middleware/authenticateToken.js
  src/middleware/errorHandler.js
  src/routes/articleRoutes.js
  src/routes/commentsRoutes.js
  src/routes/productsRoutes.js
  src/routes/userRoutes.js
  src/server.js
  start.js
  test.http
Labels: 매운맛🔥, 최종제출

#67 [김민서] sprint10
  app.js
  controllers/articleController.js
  controllers/authController.js
  controllers/commentController.js
  controllers/imageController.js
  controllers/likeController.js
  controllers/productController.js
  controllers/userController.js
  middlewares/authMiddleware.js
  middlewares/errorHandler.js
  middlewares/validationMiddleware.js
  package-lock.json
  package.json
  prisma/migrations/20240817171020_add_comment/migration.sql
  prisma/migrations/20241001022739_user_model/migration.sql
  prisma/migrations/20241001022920_product_basic_model/migration.sql
  prisma/migrations/20241001023058_article_basic_model/migration.sql
  prisma/migrations/20241001023215_user_product_article_relations/migration.sql
  prisma/migrations/20241001023807_add_basic_comment_model/migration.sql
  prisma/migrations/20241001023936_add_user_comment_relation/migration.sql
  prisma/migrations/20241001024033_add_product_comment_relation/migration.sql
  prisma/migrations/20241001024122_add_article_comment_relation/migration.sql
  prisma/migrations/20241001024157_add_basic_like_model/migration.sql
  prisma/migrations/20241001024257_add_user_like_relation/migration.sql
  prisma/migrations/20241001024348_add_product_like_relation/migration.sql
  prisma/migrations/20241001024437_add_article_like_relation/migration.sql
  prisma/migrations/20241006061701_product_update_image_array/migration.sql
  prisma/migrations/20241006061740_article_update_image_array/migration.sql
  prisma/schema.prisma
  prisma/seed.js
  routes/articleRoutes.js
  routes/authRoutes.js
  routes/commentRoutes.js
  routes/imageRoutes.js
  routes/likeRoutes.js
  routes/productRoutes.js
  routes/userRoutes.js
  server.js
  swagger/swagger.yaml
  utils/PrismaClient.js
  utils/multer.js
Labels: 최종제출
