Repository codeit-sprint-fullstack/1-Sprint-Mission-BE, pull requests merged in 2024-11, with the labels that each got.

#72 [안재민] Sprint10
  app.js
  controller/authController.js
  controller/productController.js
  package-lock.json
  package.json
  prisma/migrations/20240907023018_add_user_and_article_image/migration.sql
  prisma/migrations/20240907052004_add_article_count/migration.sql
  prisma/migrations/20240907052942_add_user_comment/migration.sql
  prisma/migrations/20240907062547_fix_article_user_table_casing/migration.sql
  prisma/migrations/20240907062739_delete_article_table_test/migration.sql
  prisma/migrations/20240907081916_fix_article_count_optional/migration.sql
  prisma/migrations/20240907085936_test/migration.sql
  prisma/migrations/20240907090024_test/migration.sql
  prisma/migrations/20240907093330_test/migration.sql
  prisma/migrations/20240907094717_test/migration.sql
  prisma/migrations/20240907105650_test/migration.sql
  prisma/migrations/20240907110338_test/migration.sql
  prisma/migrations/20240907120025_rename_count/migration.sql
  prisma/migrations/20241003110106_add_user_and_product_fields_and_id_type/migration.sql
  prisma/migrations/20241004051538_add_product_field_favorite_count/migration.sql
  prisma/migrations/20241010114448_fix_product/migration.sql
  prisma/migrations/20241010122211_add_product_tags_and_images_array_type/migration.sql
  prisma/migrations/20241010143640_add_product_favorite_count_default/migration.sql
  prisma/migrations/20241011014703_add_like_table/migration.sql
  prisma/migrations/20241011043726_fix_user_product_like_field_and_delete_favorite_count_field/migration.sql
  prisma/schema.prisma
  repository/authRepository.js
  repository/productRepository.js
  routes/articleComments.js
  routes/articles.js
  routes/auth.js
  routes/products.js
  routes/uploads.js
  service/authService.js
  service/productService.js
  structs.js
Labels: 매운맛🔥, 최종제출, 제출일에 늦은 PR입니다.

#70 [송영섭] 미션 10
  .github/pull-request-template.md
  express-mission-prisma/app.js
  express-mission-prisma/http/article.http
  express-mission-prisma/http/auth.http
  express-mission-prisma/http/comment.http
  express-mission-prisma/http/freeCommend.http
  express-mission-prisma/http/like.http
  express-mission-prisma/http/noticeBoard.http
  express-mission-prisma/http/product.http
  express-mission-prisma/http/usedCommend.http
  express-mission-prisma/package-lock.json
  express-mission-prisma/package.json
  express-mission-prisma/prisma/mock.js
  express-mission-prisma/prisma/schema.prisma
  express-mission-prisma/prisma/seed.js
  express-mission-prisma/src/config/RoleDescription
  express-mission-prisma/src/config/prisma.js
  express-mission-prisma/src/controllers/RoleDescription
  express-mission-prisma/src/controllers/articleController.js
  express-mission-prisma/src/controllers/authController.js
  express-mission-prisma/src/controllers/commentController.js
  express-mission-prisma/src/controllers/likeController.js
  express-mission-prisma/src/controllers/productController.js
  express-mission-prisma/src/middlewares/RoleDescription
  express-mission-prisma/src/middlewares/authorizationMiddleware.js
  express-mission-prisma/src/middlewares/errorHandler.js
  express-mission-prisma/src/middlewares/imgUploadHandler.js
  express-mission-prisma/src/middlewares/validateData.js
  express-mission-prisma/src/repositories/RoleDescription
  express-mission-prisma/src/repositories/articleRepository.js
  express-mission-prisma/src/repositories/authRepository.js
  express-mission-prisma/src/repositories/commentRepository.js
  express-mission-prisma/src/repositories/likeRepository.js
  express-mission-prisma/src/repositories/productRepositpry.js
  express-mission-prisma/src/services/RoleDescription
  express-mission-prisma/src/services/articleService.js
  express-mission-prisma/src/services/authService.js
  express-mission-prisma/src/services/commentService.js
  express-mission-prisma/src/services/likeService.js
  express-mission-prisma/src/services/productService.js
  express-mission-prisma/src/structs/articleStruct.js
  express-mission-prisma/src/structs/commentStruct.js
  express-mission-prisma/src/structs/likeStruct.js
  express-mission-prisma/src/structs/productStruct.js
  express-mission-prisma/src/structs/userStruct.js
  express-mission-prisma/src/utils/article/articleFilterOptions.js
  express-mission-prisma/src/utils/article/checkArticleLikeStatus.js
  express-mission-prisma/src/utils/asyncHandler.js
  express-mission-prisma/src/utils/auth/authHandler.js
  express-mission-prisma/src/utils/comment/commentFilterOptions.js
  express-mission-prisma/src/utils/createCursorResponse.js
  express-mission-prisma/src/utils/like/createLikeResponse.js
  express-mission-prisma/src/utils/like/likeFilterOptions.js
  express-mission-prisma/src/utils/like/prepareTransactionData.js
  express-mission-prisma/src/utils/product/checkProductLikeStatus.js
  express-mission-prisma/src/utils/product/createProductResponse.js
  express-mission-prisma/src/utils/product/prepareProductData.js
  express-mission-prisma/src/utils/product/productFilterOptions.js
  express-mission-prisma/struct.js
Labels: 미완성🫠, 진행중, 제출일에 늦은 PR입니다.

#77 [주영은] sprint11
  .gitignore
  controllers/articleController.js
  controllers/authController.js
  controllers/commentController.js
  controllers/productController.js
  controllers/userController.js
  index.js
  middlewares/errorHandler.js
  middlewares/validateArticle.js
  middlewares/validateProductFields.js
  middlewares/verifyToken.js
  models/index.js
  nodemon.json
  package-lock.json
  package.json
  routes/articleRoutes.js
  routes/authRoutes.js
  routes/productRoutes.js
  routes/userRoutes.js
  services/articleService.js
  services/commentService.js
  services/userService.js
  src/controllers/articleController.ts
  src/controllers/authController.ts
  src/controllers/commentController.ts
  src/controllers/productController.ts
  src/controllers/userController.ts
  src/env.ts
  src/index.ts
  src/middlewares/errorHandler.ts
  src/middlewares/imageUpload.ts
  src/middlewares/validateArticle.ts
  src/middlewares/validateProductFields.ts
  src/middlewares/verifyToken.ts
  src/models/index.ts
  src/routes/articleRoutes.ts
  src/routes/authRoutes.ts
  src/routes/commentRoutes.ts
  src/routes/productRoutes.ts
  src/routes/userRoutes.ts
  src/services/articleService.ts
  src/services/authService.ts
  src/services/commentService.ts
  src/services/productService.ts
  src/services/userService.ts
  swagger.js
  swagger_output.json
  tsconfig.json
  tsconfig.tsbuildinfo
Labels: 매운맛🔥, 최종제출

#76 [안재민] Sprint11
  app.js
  app.ts
  controller/authController.js
  controller/authController.ts
  controller/productController.js
  controller/productController.ts
  dist/app.js
  dist/controller/authController.js
  dist/controller/productController.js
  dist/dto/auth.dto.js
  dist/dto/product.dto.js
  dist/entity/product.entity.js
  dist/entity/user.entity.js
  dist/repository/authRepository.js
  dist/repository/productRepository.js
  dist/routes/auth.js
  dist/routes/products.js
  dist/routes/uploads.js
  dist/service/authService.js
  dist/service/productService.js
  dist/utils/asyncHandler.js
  dto/auth.dto.ts
  dto/product.dto.ts
  nodemon.json
  package.json
  repository/authRepository.ts
  repository/productRepository.js
  repository/productRepository.ts
  routes/articleComments.js
  routes/articles.js
  routes/auth.js
  routes/auth.ts
  routes/productComments.js
  routes/products.js
  routes/products.ts
  routes/uploads.js
  routes/uploads.ts
  server/DataSchema.js
  server/express.js
  service/authService.ts
  service/productService.js
  service/productService.ts
  tsconfig.json
  utils/asyncHandler.js
  utils/asyncHandler.ts
Labels: 매운맛🔥, 최종제출
